### ISSUE TITLE
Team cannot be deleted when having at least one employee

### ISSUE THREAD

**Issue by Danny-7** [antoinedespres/Software-Testing-Q-team#2]
Actual: Server error when trying to delete an employee
![image](https://github.com/antoinedespres/Software-Testing-Q-team/assets/58986082/804f5262-ea2c-4622-8502-c0fce442c404)

Goal: A team should be deleted when its contain at least 1 employee

Reproducibility: systematic
Product version: 1.0.3

**Comment by headdnclouds** [comment]
Issue is fixed in Version 1.0.4
