### ISSUE TITLE
Employee informations not displayed when deleting an employee

### ISSUE THREAD

**Issue by Danny-7** [antoinedespres/Software-Testing-Q-team#3]
Actual: Employee's name and email not displayed when deleting an employee 
![image](https://github.com/antoinedespres/Software-Testing-Q-team/assets/58986082/e08ca17e-bfa5-452e-adef-ae45fac0b353)

Goal: Display employee's name and email that is being deleted

Reproducibility: systematic
Product version: 1.0.3

**Comment by headdnclouds** [comment]
Issue is fixed in Version 1.0.4
